; Host fixture for the production register-preserving detour.
EXTERN CdtObserveCapture:PROC
PUBLIC CdtTestSite
.code
CdtCaptureFilter PROC
    sub rsp,28h
    call CdtObserveCapture
    add rsp,28h
    xor rax,rax
    xor rbx,rbx
    xor rcx,rcx
    xor rdx,rdx
    xor rbp,rbp
    xor rsi,rsi
    xor rdi,rdi
    xor r8,r8
    xor r9,r9
    xor r10,r10
    xor r11,r11
    xor r12,r12
    xor r13,r13
    xor r14,r14
    xor r15,r15
    pxor xmm0,xmm0
    pxor xmm1,xmm1
    pxor xmm2,xmm2
    pxor xmm3,xmm3
    pxor xmm4,xmm4
    pxor xmm5,xmm5
    pxor xmm6,xmm6
    pxor xmm7,xmm7
    pxor xmm8,xmm8
    pxor xmm9,xmm9
    pxor xmm10,xmm10
    pxor xmm11,xmm11
    pxor xmm12,xmm12
    pxor xmm13,xmm13
    pxor xmm14,xmm14
    pxor xmm15,xmm15
    ret
CdtCaptureFilter ENDP
CdtTestInvoke PROC
    push rbx
    push rbp
    push rsi
    push rdi
    push r12
    push r13
    push r14
    push r15
    sub rsp,108h
    movdqu [rsp+060h],xmm6
    movdqu [rsp+070h],xmm7
    movdqu [rsp+080h],xmm8
    movdqu [rsp+090h],xmm9
    movdqu [rsp+0a0h],xmm10
    movdqu [rsp+0b0h],xmm11
    movdqu [rsp+0c0h],xmm12
    movdqu [rsp+0d0h],xmm13
    movdqu [rsp+0e0h],xmm14
    movdqu [rsp+0f0h],xmm15
    mov QWORD PTR [rsp+50h],1234h
    mov rax,011h
    mov rcx,022h
    mov rdx,033h
    mov rbx,044h
    mov rbp,055h
    mov rsi,066h
    mov rdi,077h
    mov r8,088h
    mov r9,099h
    mov r10,0aah
    mov r11,0bbh
    mov r12,0cch
    mov r13,0ddh
    mov r14,0eeh
    mov r15,0ffh
    pcmpeqd xmm0,xmm0
    pcmpeqd xmm1,xmm1
    pcmpeqd xmm2,xmm2
    pcmpeqd xmm3,xmm3
    pcmpeqd xmm4,xmm4
    pcmpeqd xmm5,xmm5
    pcmpeqd xmm6,xmm6
    pcmpeqd xmm7,xmm7
    pcmpeqd xmm8,xmm8
    pcmpeqd xmm9,xmm9
    pcmpeqd xmm10,xmm10
    pcmpeqd xmm11,xmm11
    pcmpeqd xmm12,xmm12
    pcmpeqd xmm13,xmm13
    pcmpeqd xmm14,xmm14
    pcmpeqd xmm15,xmm15
    movdqu [rsp+20h],xmm0
    cmp eax,eax
    pushfq
    pop QWORD PTR [rsp+40h]
CdtTestSite LABEL BYTE
    mov rbx,[rsp+50h]
    pushfq
    pop QWORD PTR [rsp+48h]
    cmp rax,011h
    jne failed
    cmp rcx,022h
    jne failed
    cmp rdx,033h
    jne failed
    cmp rbx,01234h
    jne failed
    cmp rbp,055h
    jne failed
    cmp rsi,066h
    jne failed
    cmp rdi,077h
    jne failed
    cmp r8,088h
    jne failed
    cmp r9,099h
    jne failed
    cmp r10,0aah
    jne failed
    cmp r11,0bbh
    jne failed
    cmp r12,0cch
    jne failed
    cmp r13,0ddh
    jne failed
    cmp r14,0eeh
    jne failed
    cmp r15,0ffh
    jne failed
    mov rax,[rsp+48h]
    cmp rax,[rsp+40h]
    jne failed
    pcmpeqb xmm0,[rsp+20h]
    pmovmskb eax,xmm0
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm1,[rsp+20h]
    pmovmskb eax,xmm1
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm2,[rsp+20h]
    pmovmskb eax,xmm2
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm3,[rsp+20h]
    pmovmskb eax,xmm3
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm4,[rsp+20h]
    pmovmskb eax,xmm4
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm5,[rsp+20h]
    pmovmskb eax,xmm5
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm6,[rsp+20h]
    pmovmskb eax,xmm6
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm7,[rsp+20h]
    pmovmskb eax,xmm7
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm8,[rsp+20h]
    pmovmskb eax,xmm8
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm9,[rsp+20h]
    pmovmskb eax,xmm9
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm10,[rsp+20h]
    pmovmskb eax,xmm10
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm11,[rsp+20h]
    pmovmskb eax,xmm11
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm12,[rsp+20h]
    pmovmskb eax,xmm12
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm13,[rsp+20h]
    pmovmskb eax,xmm13
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm14,[rsp+20h]
    pmovmskb eax,xmm14
    cmp eax,0FFFFh
    jne failed
    pcmpeqb xmm15,[rsp+20h]
    pmovmskb eax,xmm15
    cmp eax,0FFFFh
    jne failed
    mov eax,1
    jmp finish
failed:
    xor eax,eax
finish:
    movdqu xmm6,[rsp+060h]
    movdqu xmm7,[rsp+070h]
    movdqu xmm8,[rsp+080h]
    movdqu xmm9,[rsp+090h]
    movdqu xmm10,[rsp+0a0h]
    movdqu xmm11,[rsp+0b0h]
    movdqu xmm12,[rsp+0c0h]
    movdqu xmm13,[rsp+0d0h]
    movdqu xmm14,[rsp+0e0h]
    movdqu xmm15,[rsp+0f0h]
    add rsp,108h
    pop r15
    pop r14
    pop r13
    pop r12
    pop rdi
    pop rsi
    pop rbp
    pop rbx
    ret
CdtTestInvoke ENDP
END

