// GENERATED from rendering-features.txt by tools/gen-features.sh - do not edit.
// Build 25116796. The ids are a checked hint, not trusted input: Invoke() reads
// the id back out of the resolved stub and refuses on a mismatch, so a table
// that has gone stale on a new build reports itself instead of firing the wrong
// feature.
#pragma once

namespace ch { namespace dbg {

struct FeatureRow { const char* name; int id; };

constexpr FeatureRow kFeatures[] = {
    { "LightingOnly", 0 },
    { "DirectLighting", 1 },
    { "DirectionalLight", 2 },
    { "PointLight", 3 },
    { "PointLightFlickering", 4 },
    { "AreaLight", 5 },
    { "SkyLight", 6 },
    { "AtmosphericScattering", 7 },
    { "Cloud", 8 },
    { "RenderParticipatingMedia", 9 },
    { "ShadowAO", 10 },
    { "ShadowAOInterleaved", 11 },
    { "ShadowAOFiltering", 12 },
    { "ShadowAOFilteringSeparable", 13 },
    { "DirectionalLightShadow", 15 },
    { "DirectionalLightTranslucentShadow", 16 },
    { "NearFieldShadow", 17 },
    { "PointLightShadow", 18 },
    { "ContactShadow", 19 },
    { "PointLightUseShadowBits", 20 },
    { "VoxelAO", 21 },
    { "HBAO", 22 },
    { "HBAONeighborReuse", 23 },
    { "SSSSS", 24 },
    { "HighPrecisionNormalBuffer", 25 },
    { "HighPrecisionVelocityBuffer", 26 },
    { "HighPrecisionSceneColorBuffer", 27 },
    { "SpecularVoxelRaymarching", 28 },
    { "ScreenSpaceReflections", 29 },
    { "EnvironmentMaps", 30 },
    { "EnvironmentMapsUseRaymarching", 31 },
    { "UpdateEnvironmentMaps", 32 },
    { "EnvironmentSkyMapsTerrainRendering", 33 },
    { "PreRenderEnvironmentMapsForMetallics", 34 },
    { "GlobalIllumination", 35 },
    { "DiffuseGlobalIllumination", 36 },
    { "DiffuseGlobalIlluminationDownsampled", 38 },
    { "DiffuseGlobalIlluminationScreenSpaceRays", 39 },
    { "DiffuseGlobalIlluminationLocalLights", 40 },
    { "DiffuseGlobalIlluminationLocalLightsUseSeparatePass", 41 },
    { "DiffuseGlobalIlluminationUseIndirectCache", 42 },
    { "DiffuseGlobalIlluminationTiledRadianceCache", 43 },
    { "DiffuseGlobalIlluminationTiledRadianceCacheFiltering", 44 },
    { "DiffuseGlobalIlluminationFiltering", 45 },
    { "SpecularGlobalIllumination", 47 },
    { "SpecularGlobalIlluminationFiltering", 48 },
    { "SpecularGlobalIlluminationFilteringSeparable", 49 },
    { "SpecularGlobalIlluminationHighQuality", 50 },
    { "GlobalIlluminationMultipleBounce", 51 },
    { "Raytracing", 52 },
    { "RaytracedDiffuseGI", 53 },
    { "RaytracedSpecularGI", 54 },
    { "GenerateSceneVoxels", 55 },
    { "GenerateSceneVoxelsFromMainView", 56 },
    { "GenerateSceneVoxelsFromObjects", 57 },
    { "GenerateVoxelsFrameDistribution", 58 },
    { "ReadbackVoxelGenerationStatistics", 60 },
    { "UseBilinearSamplerForDiffuseGI", 62 },
    { "UseBilinearSamplerForSpecularGI", 63 },
    { "InjectSceneLightsToSceneVoxels", 64 },
    { "VisualizeClipmaps", 65 },
    { "ClearSceneVoxels", 66 },
    { "ClearRadianceVoxels", 67 },
    { "ClearSignedDistanceVoxels", 68 },
    { "ClearDynamicSceneVoxels", 69 },
    { "GenerateMipLevels", 70 },
    { "WeatherRain", 71 },
    { "VisualizeOverdraw", 72 },
    { "VisualizeEffectOverdraw", 73 },
    { "VisualizeVertexNormalError", 74 },
    { "VisualizeTextureNormalError", 76 },
    { "VisualizeTexelDensity", 77 },
    { "VisualizeTransmission", 78 },
    { "VisualizeLightOverdraw", 79 },
    { "VisualizeDiffuseReflectance", 80 },
    { "VisualizeDiffuseReflectanceMode", 81 },
    { "MultithreadedPresent", 87 },
    { "TiledDispatch", 88 },
    { "TemporalAA", 90 },
    { "TemporalAAUpsample", 91 },
    { "TemporalAAUpsampleBicubic", 92 },
    { "TemporalAANeighborhoodClamping", 94 },
    { "TemporalAABilateralWeights", 95 },
    { "PostProcessSharpen", 97 },
    { "PostProcessDepthOfField", 98 },
    { "PostProcessMotionBlur", 99 },
    { "PostProcessEyeAdaptation", 100 },
    { "PostProcessGlare", 101 },
    { "CharacterPBDThreadDistribution", 102 },
    { "MipLODBias", 103 },
    { "AnisotropicTextureFilteringForTerrain", 104 },
    { "LargeScaleAutomaticPlacement", 106 },
    { "SmallScaleAutomaticPlacement", 107 },
    { "DeformableSurface", 109 },
    { "VoxelGeometry", 110 },
    { "TreeWind", 115 },
    { "PreExposure", 116 },
    { "LargeScaleDetailMapping", 119 },
    { "ScreenSpaceDisplacementMapping", 120 },
};
constexpr int kFeatureCount = int(sizeof(kFeatures) / sizeof(kFeatures[0]));

// Registered, but bound to the shared stub 0x140353C70 whose whole body is
// `ret`. They can be invoked and will do nothing; the invoker refuses them so
// a null result is never mistaken for a measurement.
constexpr const char* kNoOpFeatures[] = {
    "AsyncCompute",
    "DiffuseGlobalIlluminationAOOnly",
    "EncodeBaseColor",
    "LightingInterleaved",
    "LightingInterleavedRenderDirectionalLightsWithGI",
    "ReflectorLight",
    "SortIndirectCommands",
};
constexpr int kNoOpCount = int(sizeof(kNoOpFeatures) / sizeof(kNoOpFeatures[0]));

}}  // namespace ch::dbg

