# The JSON definition is the only editable allowlist/offset source. Reconfigure
# automatically when it changes; never silently fall back to embedded old data.
set(CDT_NATIVE_DEFINITION "${CDT_ROOT}/definitions/build-25116796.json")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CDT_NATIVE_DEFINITION}")
file(READ "${CDT_NATIVE_DEFINITION}" cdt_profile)

function(cdt_require out type)
    string(JSON actual_type ERROR_VARIABLE error TYPE "${cdt_profile}" ${ARGN})
    if(error OR NOT actual_type STREQUAL "${type}")
        message(FATAL_ERROR "Native contract ${ARGN}: required ${type} field missing or malformed (${error})")
    endif()
    string(JSON value GET "${cdt_profile}" ${ARGN})
    set(${out} "${value}" PARENT_SCOPE)
endfunction()
function(cdt_number out)
    cdt_require(value NUMBER ${ARGN})
    if(NOT value MATCHES "^[0-9]+$" OR value GREATER 2147483647)
        message(FATAL_ERROR "Native contract ${ARGN}: bounded unsigned integer required")
    endif()
    set(${out} "${value}" PARENT_SCOPE)
endfunction()
function(cdt_bytes out size_out text)
    string(REGEX REPLACE "[ \t\r\n]" "" compact "${text}")
    string(LENGTH "${compact}" length)
    math(EXPR remainder "${length} % 2")
    if(NOT compact MATCHES "^[0-9A-Fa-f]+$" OR remainder OR length GREATER 256)
        message(FATAL_ERROR "Native contract exact signature must contain 1..128 complete hex bytes (no wildcards)")
    endif()
    math(EXPR count "${length} / 2")
    string(REGEX REPLACE "(..)" "0x\\1," result "${compact}")
    set(${out} "${result}" PARENT_SCOPE)
    set(${size_out} "${count}" PARENT_SCOPE)
endfunction()

cdt_number(CDT_SCHEMA schemaVersion)
cdt_number(CDT_NATIVE_SCHEMA nativeCapture schemaVersion)
cdt_require(CDT_BUILD STRING steamBuildId)
cdt_require(CDT_CONTRACT_ID STRING nativeCapture contractId)
cdt_require(status STRING status)
cdt_require(native_status STRING nativeCapture status)
cdt_require(exact BOOLEAN nativeCapture requiresExactExecutable)
if(NOT CDT_SCHEMA EQUAL 1 OR NOT CDT_NATIVE_SCHEMA EQUAL 1 OR
   NOT status STREQUAL "locally-validated" OR NOT native_status STREQUAL "locally-validated" OR NOT exact OR
   NOT CDT_CONTRACT_ID STREQUAL "manylights-filter-25116796-v1")
    message(FATAL_ERROR "Native contract is not a supported, explicitly validated exact-executable contract")
endif()
cdt_require(hash STRING executableSha256)
string(LENGTH "${hash}" hash_length)
if(NOT hash_length EQUAL 64 OR NOT hash MATCHES "^[0-9A-Fa-f]+$")
    message(FATAL_ERROR "Native contract executableSha256 must contain exactly 32 bytes")
endif()
string(REGEX REPLACE "(..)" "0x\\1," CDT_EXE_HASH "${hash}")
cdt_number(CDT_SCENE_GLOBAL engineLights sceneGlobalRva)
cdt_number(camera_global engineCamera cameraGlobalRva)
if(CDT_SCENE_GLOBAL EQUAL 0 OR NOT CDT_SCENE_GLOBAL EQUAL camera_global)
    message(FATAL_ERROR "Native and managed scene roots disagree")
endif()
cdt_number(CDT_HOOK_RVA nativeCapture hookRva)
cdt_require(hook STRING nativeCapture hookSignature)
cdt_bytes(CDT_HOOK_BYTES CDT_HOOK_SIZE "${hook}")
if(NOT CDT_HOOK_SIZE EQUAL 25)
    message(FATAL_ERROR "The current thunk contract requires the validated 25-byte hook signature")
endif()
foreach(pair "output;r12" "command;rbx" "counter;r15" "owner;r13")
    list(GET pair 0 name)
    list(GET pair 1 expected)
    cdt_require(actual STRING nativeCapture registers ${name})
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Native ${name} register differs from the reviewed assembly thunk")
    endif()
endforeach()

cdt_require(contexts ARRAY nativeCapture contextSignatures)
string(JSON CDT_CONTEXT_COUNT LENGTH "${contexts}")
if(CDT_CONTEXT_COUNT LESS 1 OR CDT_CONTEXT_COUNT GREATER 8)
    message(FATAL_ERROR "Native contract requires 1..8 bounded provenance signatures")
endif()
set(CDT_CONTEXT_ARRAYS "")
set(CDT_CONTEXT_ENTRIES "")
math(EXPR last_context "${CDT_CONTEXT_COUNT} - 1")
foreach(index RANGE 0 ${last_context})
    cdt_number(rva nativeCapture contextSignatures ${index} rva)
    cdt_require(bytes STRING nativeCapture contextSignatures ${index} bytes)
    cdt_require(purpose STRING nativeCapture contextSignatures ${index} purpose)
    cdt_bytes(values length "${bytes}")
    if(rva EQUAL 0 OR length LESS 8 OR purpose STREQUAL "")
        message(FATAL_ERROR "Native provenance requires a nonzero RVA and evidence purpose")
    endif()
    string(APPEND CDT_CONTEXT_ARRAYS "inline constexpr std::array<std::uint8_t, ${length}> ContextBytes${index}{${values}};\n")
    string(APPEND CDT_CONTEXT_ENTRIES "    ContextSignature{${rva}ULL, ContextBytes${index}},\n")
endforeach()
foreach(key innerOffset strideOffset countOffset resourceOffset commandHolderOffset nativeListOffset ownerBankIndexOffset)
    cdt_number(CDT_WRAPPER_${key} nativeCapture wrapper ${key})
endforeach()
foreach(key rootPointerOffset byteCount frameOffset screenOffset positionOffset directionOffset viewRelativeOffset earthRadiusOffset earthRadius)
    cdt_number(CDT_SCENE_${key} nativeCapture scene ${key})
endforeach()
foreach(key recordCount recordStride counterBytes validCounterByteOffset)
    cdt_number(CDT_GPU_${key} nativeCapture gpu ${key})
endforeach()
cdt_require(state STRING nativeCapture gpu resourceState)
if(NOT state STREQUAL "unordered-access")
    message(FATAL_ERROR "Native resource state differs from the reviewed post-dispatch copy contract")
endif()
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
configure_file("${CMAKE_CURRENT_LIST_DIR}/native_contract.generated.h.in"
    "${CMAKE_CURRENT_BINARY_DIR}/generated/native_contract.generated.h" @ONLY)
